### ISSUE TITLE
Task #3988 for VoidChest v1.8.8.1 generated an exception

### ISSUE THREAD

**Issue by DexterSK** [Shin1gamiX/VoidChest#13]
[21:39:42 WARN]: [VoidChest-1.8.8.1] Task #3988 for VoidChest v1.8.8.1 generated an exception
java.lang.NoSuchFieldError: shops
        at me.shin1gamix.voidchest.ecomanager.customeco.VoidChestShopGUIPlusEconomy.getProfit(VoidChestShopGUIPlusEconomy.java:37) ~[VoidChest-1.8.8.1.jar:?]
        at me.shin1gamix.voidchest.ecomanager.customeco.copy.AVoidChestEconomy.getProfit(AVoidChestEconomy.java:59) ~[VoidChest-1.8.8.1.jar:?]
        at me.shin1gamix.voidchest.ecomanager.customeco.copy.AVoidChestEconomy.initiateSell(AVoidChestEconomy.java:159) ~[VoidChest-1.8.8.1.jar:?]
        at me.shin1gamix.voidchest.ecomanager.customeco.copy.AVoidChestEconomy.initiateSell(AVoidChestEconomy.java:403) ~[VoidChest-1.8.8.1.jar:?]
        at me.shin1gamix.voidchest.tasks.SellTask.run(SellTask.java:52) ~[VoidChest-1.8.8.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

---

VoidChest v1.8.8.1

Current: git-Purpur-1613 (MC: 1.18.2)

**Comment by Shin1gamiX** [comment]
ShopGuiPlus updated their plugin. Having changed their code, it broke support for other plugins. Voidchest was updated and has been fixed.
